services:
  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend-container
  backend:
    image: backend
    build: ./backend
    container_name: backend-container
  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
